version: "3.8"

services:
  backend:
    image: munfung/backend-api:latest
    container_name: backend-container
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - app-network

  frontend:
    image: munfung/frontend-app:latest
    container_name: frontend-container
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
