version: "3.8"
services:
  backend:
    image: munfung/backend-api:latest # Use the latest pushed image
    ports:
      - "5000:5000"
    networks:
      - devops-network

  frontend:
    image: munfung/frontend-app:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:5000 # Uses internal network
    networks:
      - devops-network

networks:
  devops-network:
